name: 'Setup Terraform e Terragrunt'
description: 'Configura o Terraform e, opcionalmente, o Terragrunt CLI no fluxo de trabalho do GitHub Actions.'
author: 'VNicoE'

inputs:
  cli_config_credentials_hostname:
    description: 'O hostname de uma instância HCP Terraform/Terraform Enterprise para colocar dentro do bloco de credenciais do arquivo de configuração do Terraform CLI. O padrão é `app.terraform.io`.'
    default: 'app.terraform.io'
    required: false
  cli_config_credentials_token:
    description: 'O token da API para uma instância HCP Terraform/Terraform Enterprise para colocar dentro do bloco de credenciais do arquivo de configuração do Terraform CLI.'
    required: false
  terraform_version:
    description: 'A versão do Terraform CLI a ser instalada. Pode ser uma versão específica ou uma string de restrição como `<1.13.0` para instalar a última versão que satisfaça a condição. O valor `latest` instala a versão mais recente. Padrão: `latest`.'
    default: 'latest'
    required: false
  terragrunt_version:
    description: 'A versão do Terragrunt CLI a ser instalada. Padrão: `v0.67.16`. Se não quiser instalar o Terragrunt, deixe em branco.'
    default: '0.67.16'
    required: false
  terraform_wrapper:
    description: 'Se deve ou não instalar um wrapper que exponha o STDOUT, STDERR, e o código de saída da execução do Terraform como outputs. Padrão: `true`.'
    default: 'true'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'terminal'
  color: 'purple'
